#  Defining Users, Roles, and Permissions in AMQ Broker

=== Setting up user authentication by creating new JAAS login modules 

  You can configure new JAAS login modules, which are stored in an OpenShift secret, to authenticate users with AMQ Broker. In the ActiveMQArtemis custom resource (CR), you must assign broker permissions to roles that are defined in the new login module.

** Procedure

    Create a text file with your new JAAS login modules configuration and save the file as login.config. By saving the file as login.config, the correct key is inserted in the secret that you create from the text file.


    You must include the credentials required by the Operator to authenticate with the broker in the login.config file. You can do this by adding the default properties login module, which uses the artemis-users.properties and artemis.roles properties files, as shown in the following examples. Alternatively, you can add the contents of the artemis-users.properties and artemis.roles.properties to other user and roles properties files configured in the login.config file.

** Example login.config files

    The following example has a properties login module that is used to authenticate users and the default properties login module required by the Operator to authenticate with the broker:
[source,yaml]
----
      activemq {
          org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
            reload=false
            org.apache.activemq.jaas.properties.user="artemis-users.properties"
            org.apache.activemq.jaas.properties.role="artemis-roles.properties"
            baseDir="/home/jboss/amq-broker/etc";
      };
----

      Place the properties files that contain the credentials used by the Operator to authenticate with the broker at the end of the login.config file. This ensures that the properties files in all login modules are loaded when the broker authenticates the Operator. Otherwise, the custom resource might have a status message showing that some property files are not visible on the broker, until all login modules are used.

      If the login.config file you created includes a properties login module, ensure that the users and roles files specified in the module contain user and role information. For example:
[source,yaml]
----
      new-users.properties
        ruben=ruben01!
        anne=anne01!
        rick=rick01!
        bob=bob01!

      new-roles.properties
        admin=ruben, rick
        group1=bob
        group2=anne
----
      Use the oc create secret command to create a secret from the text file that you created with the new login module configuration. If the login module configuration includes a properties login module, also include the associated users and roles files in the secret. For example:
[source,bash]
----
oc create secret generic custom-jaas-config --from-file=login.config --from-file=new-users.properties --from-file=new-roles.properties
----

      The secret name must have a suffix of -jaas-config so the Operator can recognize that the secret contains login module configuration and propagate any updates to each broker pod.

      For more information about how to create secrets, see Secrets in the Kubernetes documentation.

      Add the secret you created to the custom resource (CR) instance for your broker deployment.

      Create an extraMounts element and a secrets element and add the name of the secret. The following example adds a secret named custom-jaas-config to the CR.
[source,yaml]
----
        deploymentPlan:
          ...
          extraMounts:
            secrets:
            - "custom-jaas-config"
          ...
----
      In the CR, grant permissions to the roles that are configured on the broker.

      In the spec section of the CR, add a brokerProperties element and add the permissions. You can grant a role permissions to a single address. Or, you can specify a wildcard match using the # sign to grant a role permissions to all addresses. For example:
[source,yaml]
----
          spec:
            ...
            brokerProperties:
            - securityRoles.#.group2.send=true
            - securityRoles.#.group1.consume=true
            - securityRoles.#.group1.createAddress=true
            - securityRoles.#.group1.createNonDurableQueue=true
            - securityRoles.#.group1.browse=true
            ...
----
      In the example, the group2 role is assigned send permissions to all addresses and the group1 role is assigned consume, createAddress, createNonDurableQueue and browse permissions to all addresses.


      In a Java properties file, a colon (:) is a reserved character that is used to separate a key and a value in a key/value pair. If you want to grant permissions to a fully qualified queue name (FQQN), which consists of an address name and a queue name separated by colons (::), you must use the backslash (\) character to escape the colon characters in the FQQN. For example:
[source,yaml]
----
      spec:
        ...
        brokerProperties:
        - 'securityRoles."my-address\:\:my-queue".group2.send=true'
----        